[package]
name = "deduplicate"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.7"
sha2 = "0.10.2"
os_str_bytes = "6.1.0"